# Generated by Django 4.1.2 on 2022-10-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlShortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longurl", models.CharField(max_length=255)),
                ("shorturl", models.SlugField(max_length=8)),
            ],
        ),
    ]
