# Generated by Django 4.1.2 on 2022-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='user_ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
